### ISSUE TITLE
--model_dir=<path_to_tooth-detection>/tooth-detection/models/transfer/new_version  :  no "transfer" folder

### ISSUE THREAD

**Issue by cpoptic** [clemkoa/tooth-detection#10]
Hi Clement, under the `training` section, you say to call train.py with arguments
`--model_dir=<path_to_tooth-detection>/tooth-detection/models/transfer/new_version`

but there is no folder `/models/transfer/new_version`.  Where do you get this folder from?  Thanks

**Comment by hbiancot13** [comment]
Hi Clément, I am also interested in the answer!

Thanks !

**Comment by clemkoa** [comment]
Yes because I haven't comitted the trained model. It's a folder where I save my models. 
You can find more info on the tf object detection training here https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/running_locally.md
