### ISSUE TITLE
pipeline_config_path Issue

### ISSUE THREAD

**Issue by kprc369** [clemkoa/tooth-detection#12]
Hi 
I have some question about pipeline_config_path

--pipeline_config_path=<path_to_tooth-detection>/tooth-detection/models/transfer/faster_rcnn_resnet50_coco.config \

There is no /models/transfer ....

Is it Treatment folder....?

**Comment by clemkoa** [comment]
Hi, apologies for the delay

Yes it is either models/treatment or models/index depending on the task that you want (getting tooth indices or showing all treatments)

I have updated the readme accordingly
