### ISSUE TITLE
golden_label_map.pbtxt and train.record

### ISSUE THREAD

**Issue by javkhlant** [clemkoa/tooth-detection#19]
Hi Clement!
This is a great project and I'm excited to run it.
I have followed your installation guide.
When I run the training command the following errors show up:
tensorflow.python.framework.errors_impl.NotFoundError: /tooth-detection/data/golden_label_map.pbtxt; No such file or directory
or
RuntimeError: Did not find any input files matching the glob pattern ['/tooth-detection/data/train.record']

How do I create those files? Could you please give me a little hint to run it?
Thank you kindly

**Comment by clemkoa** [comment]
Hi, the two missing files are data files and I cannot share them for patient privacy reasons, unfortunately. I understand this is frustrastring because you won't be able to run the model without them, but I am not allowed to share this sensitive data.
