### ISSUE TITLE
Any chance to continue this work on other Cloud platforms ?

### ISSUE THREAD

**Issue by AndrzejRPiotrowski** [clemkoa/tooth-detection#21]

**Comment by goodengineer** [comment]
Hi, good question. 1) Which platform, MS Azure, Amazon? 2) What do you mean by continue, please write in details which functionality, interface, which code to add?

**Comment by clemkoa** [comment]
Hi @AndrzejRPiotrowski ,

I only provided the scripts to run it automatically on GCP, but the code (training, eval, model) is platform-agnostic. It should work on any platform, it's only up to you to make it run on the platform you want.
This repo has been on hold for a little bit (you can see there hasn't been any commit in a while), I'm also not sure all of the API of tensorflow-models is still up to date. The dataset for this repo is private, so you don't have a good way to train the model by yourself. While I generally encourage contributions, I'm not sure the changes you mentioned would be relevant for this repository.

**Comment by AndrzejRPiotrowski** [comment]
> Hi, good question. 1) Which platform, MS Azure, Amazon? 2) What do you mean by continue, please write in details which functionality, interface, which code to add?

Amazon. I was thinking of having this as "self" diagnostic API :) For people who want to help build the model. So i was hoping that some patients can send x-ray as "free-of-charge" and help build this model.

To be specific, simple CRUD app with x-ray add to model trainning.

**Comment by AndrzejRPiotrowski** [comment]
> Hi @AndrzejRPiotrowski ,
> 
> I only provided the scripts to run it automatically on GCP, but the code (training, eval, model) is platform-agnostic. It should work on any platform, it's only up to you to make it run on the platform you want.
> This repo has been on hold for a little bit (you can see there hasn't been any commit in a while), I'm also not sure all of the API of tensorflow-models is still up to date. The dataset for this repo is private, so you don't have a good way to train the model by yourself. While I generally encourage contributions, I'm not sure the changes you mentioned would be relevant for this repository.

Thank You for the reply.

Most interesting topic is mode set :
- how many x-ray images ?
- how long it was working :) to get a good detection rate ?
- what was the best detection rate ?

**Comment by Bernstein7z** [comment]
- size of images?
- labeled with rect angle or polygon?

**Comment by clemkoa** [comment]
Hi all,

You can find some answers to your questions here https://clemkoa.github.io/dental/2018/06/10/deep-learning-dental-x-ray.html
I welcome any contribution if you want to make this model work on other cloud platforms, and if you want to build a webapp for image upload. You can create yourself a dummy dataset by scrapping a few panoramic x-ray pictures from google image.

**Comment by AndrzejRPiotrowski** [comment]
@clemkoa Great. Thank You with this.

**Comment by AndrzejRPiotrowski** [comment]
@clemkoa 
Still waiting for my x-rays due to i want to have at least 100. Will be in contact beause i am sure lot of people here will want to help.
Great project again.

My idea is to have easy access to people x-ray using web app - they have some sort of info about x-ray - i have more x-rays to play with - not in comercial way.

**Comment by clemkoa** [comment]
I am closing this issue because it's been inactive for a while. Hope you manage to build your dataset - good luck!
