### ISSUE TITLE
Dataset link

### ISSUE THREAD

**Issue by Sofia-Oles** [clemkoa/tooth-detection#29]
Hello, could you share this dataset for study goal? Thanks in advance! DM s.oleskevych@gmail.com

**Comment by shashankshirke** [comment]
Hi @Sofia-Oles 

Did you manage to get the dataset that was used for this model training? If yes, I would like to get access to the dataset.

**Comment by QiuDingQian** [comment]
Hello! May I ask if you have obtained this dataset and would like to share it with me.
Thank you!

**Comment by clemkoa** [comment]
Hi all, sorry but the dataset is not available to the public for privacy reasons. I've been trying to get approval for a while but I wouldn't hold my breath, it looks pretty unlikely at this stage.
