### ISSUE TITLE
more details about installation and operation

### ISSUE THREAD

**Issue by CAOLINAN** [clemkoa/tooth-detection#7]
I don't konw which python in this project.I hope to get some information about it and some more details about operation.

**Comment by clemkoa** [comment]
Hi,

Python version is 2.7.16. I plan on releasing a true installation script. Right now things are still a work in progress, but I will update the readme soon for installation steps. The dataset is not public because of its medical nature, we are working on releasing it as well.

**Comment by CAOLINAN** [comment]
Thank you~Hope to see it.

**Comment by CAOLINAN** [comment]
Hi, it has passed 11 days.I think you may commit a pip script.Just using 'pip freeze >requirements.txt' command in your project root and will get a text named requirements.And you can commit it.It contains some dependency packages.Thank you.

**Comment by clemkoa** [comment]
Hi,

I updated the readme. Be aware of a few things:
- dataset is not public yet so I can't give instructions about it in the README
- everything is dependent on Tensorflow Object Detection API and Google Cloud SDK, which adds steps to the installation.

I'd like to switch do python 3.7 but i don't think the Object Detection API supports it.

**Comment by CAOLINAN** [comment]
Thank you for updating.You're right.The Object Detection API doesn't support python3.But I found a solution.Here is the URL: 'https://stackoverflow.com/questions/49311195/how-to-install-coco-pythonapi-in-python3'.It said that you can use the python package 2to3 if you want to switch to python3 from python2.Hope it can help you~
